Implement image management commands
JurajNyiri/pytapo pull request #7
Opened 2020-11-27 15:23 UTC by Depau

Adds:

- `get/setImageFlipVertical` - "Invert image" in the app
- `get/setLightFrequencyMode` - "Light frequency" in the app, reduces flickering
- `get/setLensDistortionCorrection`

2020-11-27 15:27 UTC, Depau commented
By the way, here's the very ugly but useful frida.re script I'm using to reverse engineer the commands.

https://gist.github.com/Depau/f6186475c46c25a766b29a5a2e5af964

I ordered a new cam and I'm planning to implement initial setup since I would have **really** avoided creating an account just to set it up from the app and enable RTSP.

My plan is to get them to work completely offline with the features I actually need.

2020-11-27 23:38 UTC, JurajNyiri requested changes
This looks good! 👍 

Please rebase your changes on 1.2 branch.

This branch includes automated tests for every function (except format). Please check out test_pytapo.py in root and [new test instructions](https://github.com/JurajNyiri/pytapo/blob/1.2/README.md#test-instructions). Could you please add unit tests for your new functions to keep the 100% coverage?

I also sent you an email asking some questions regarding this PR, please check it out.

2020-11-27 23:38 UTC, JurajNyiri commented on pytapo/__init__.py
> +        return data["image"]["switch"]["light_freq_mode"]
This function is now implemented in 1.2 as getCommonImage, I needed to figure out how to get dayNightMode when creating tests.

2020-12-05 19:46 UTC, JurajNyiri approved these changes

2020-12-05 19:46 UTC, merged